// generated by mBlock5 for mBot Ranger
// codes make you happy

#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>
#include <MeAuriga.h>

MeUltrasonicSensor ultrasonic_7(7);
MeLightSensor lightsensor_12(12);
MeLineFollower linefollower_9(9);
MeEncoderOnBoard Encoder_1(SLOT1);
MeEncoderOnBoard Encoder_2(SLOT2);

float wall = 0;
float WallDetected = 0;
float DistToWall = 0;
float Duration = 0;
float RoomSize = 0;
float CmPerSecond = 0;
float Speed = 0;

void detectWall (){
    WallDetected = 0;
    if(ultrasonic_7.distanceCm() < 25){
        WallDetected = 1;

    }

}

void isr_process_encoder1(void)
{
  if(digitalRead(Encoder_1.getPortB()) == 0){
    Encoder_1.pulsePosMinus();
  }else{
    Encoder_1.pulsePosPlus();
  }
}
void isr_process_encoder2(void)
{
  if(digitalRead(Encoder_2.getPortB()) == 0){
    Encoder_2.pulsePosMinus();
  }else{
    Encoder_2.pulsePosPlus();
  }
}
void move(int direction, int speed)
{
  int leftSpeed = 0;
  int rightSpeed = 0;
  if(direction == 1){
    leftSpeed = -speed;
    rightSpeed = speed;
  }else if(direction == 2){
    leftSpeed = speed;
    rightSpeed = -speed;
  }else if(direction == 3){
    leftSpeed = -speed;
    rightSpeed = -speed;
  }else if(direction == 4){
    leftSpeed = speed;
    rightSpeed = speed;
  }
  Encoder_1.setTarPWM(leftSpeed);
  Encoder_2.setTarPWM(rightSpeed);
}
void lineFollow (){
    while(1) {
        while(!(linefollower_9.readSensors() > 0))
        {
          _loop();

          move(1, 30 / 100.0 * 255);
          _delay(0.1);
          move(1, 0);
          if(ultrasonic_7.distanceCm() < 25){
              turnRight();
              detectWall();
              if(WallDetected == 1.000000){
                  turnAround();
                  detectWall();
                  if(WallDetected == 1.000000){
                      turnLeft();

                  }

              }

          }

        }
        if(linefollower_9.readSensors() == 1.000000){
            nudgeLeft();

        }
        if(linefollower_9.readSensors() == 2.000000){
            nudgeRight();

        }

        _loop();
    }

}
void nudgeLeft (){
    Encoder_1.setTarPWM(0);
    Encoder_2.setTarPWM(0);
    _delay(0.5);
    while(!(linefollower_9.readSensors() == 0.000000))
    {
      _loop();

      move(3, 15 / 100.0 * 255);
      _delay(0.1);
      move(3, 0);

    }
    lineFollow();

}
void turnLeft (){
    Encoder_1.setTarPWM(0);
    Encoder_2.setTarPWM(0);
    _delay(0.5);

    move(3, 100 / 100.0 * 255);
    _delay(1.5);
    move(3, 0);
    _delay(1);
    lineFollow();

}
void nudgeRight (){
    Encoder_1.setTarPWM(0);
    Encoder_2.setTarPWM(0);
    _delay(0.5);
    while(!(linefollower_9.readSensors() == 0.000000))
    {
      _loop();

      move(4, 15 / 100.0 * 255);
      _delay(0.1);
      move(4, 0);

    }
    lineFollow();

}
void turnRight (){
    Encoder_1.setTarPWM(0);
    Encoder_2.setTarPWM(0);
    _delay(0.5);

    move(4, 100 / 100.0 * 255);
    _delay(1.5);
    move(4, 0);
    _delay(1);
    lineFollow();

}
void turnAround (){
    Encoder_1.setTarPWM(0);
    Encoder_2.setTarPWM(0);
    _delay(0.5);

    move(3, 50 / 100.0 * 255);
    _delay(5);
    move(3, 0);
    _delay(1);
    lineFollow();

}

void _delay(float seconds) {
  if(seconds < 0.0){
    seconds = 0.0;
  }
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  randomSeed((unsigned long)(lightsensor_12.read() * 123456));
  TCCR1A = _BV(WGM10);
  TCCR1B = _BV(CS11) | _BV(WGM12);
  TCCR2A = _BV(WGM21) | _BV(WGM20);
  TCCR2B = _BV(CS21);
  attachInterrupt(Encoder_1.getIntNum(), isr_process_encoder1, RISING);
  attachInterrupt(Encoder_2.getIntNum(), isr_process_encoder2, RISING);

  lineFollow();

}

void _loop() {
  Encoder_1.loop();
  Encoder_2.loop();
}

void loop() {
  _loop();
}
